application: epihourtesting
version: 1
runtime: python
api_version: 1

handlers:
# The root URL (/) is handled by the main.py script.  No other URLs match this pattern.
- url: /
  script: main.py

# The URL /index.html is also handled by the index.py script.
- url: /index\.html
  script: main.py

- url: /images
  static_dir: static/images

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

# Handler for the favicon - For faster appengine
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico


# All other URLs use the not_found.py script.
- url: /.*
  script: not_found.py
