application: epihour
version: 4
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

# Handler for the favicon - For faster appengine
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: main.py
